import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: "Contact",
    description: "Generated by create next app",
  };

function ConatctLayout() {
  return (
    <div>ConatctL</div>
  )
}

export default ConatctLayout;