import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: "Contact",
    description: "Generated by create next app",
  };

function ConatctLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>{children}</div>
  )
}

export default ConatctLayout;