import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "About Me",
    description: "Generated by create next app",
  };

function AboutLayout() {
  return (
    <></>
  )
}

export default AboutLayout;