import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "About Me",
    description: "Generated by create next app",
  };

function AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>{children}</main>
  )
}

export default AboutLayout;