import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: "My Projects",
    description: "Generated by create next app",
  };

function ProjectsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main> {children} </main>
  )
}

export default ProjectsLayout;