import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: "My Projects",
    description: "Generated by create next app",
  };

function ProjectsLayout() {
  return (
    <></>
  )
}

export default ProjectsLayout;