import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ux/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        <main className="pt-20 h-screen bg-[linear-gradient(to_right,rgba(229,231,235,0.08)_1px,transparent_1px),linear-gradient(to_bottom,rgba(229,231,235,0.08)_1px,transparent_1px)] bg-[size:15px_15px]" >
          <div className="m-auto w-5xl">{children}</div>
        </main>
      </body>
    </html> 
  );
}
